### ISSUE TITLE
Id editor layout overlays TM menus

### ISSUE THREAD

**Issue by JorgeMartinezG** [hotosm/tasking-manager#2554]
Based on feedback received from testing mapathon:

![image](https://user-images.githubusercontent.com/3285923/77343541-d6893d00-6cff-11ea-8b68-b42226c991c3.png)

**Comment by willemarcel** [comment]
Solved by https://github.com/openstreetmap/iD/commit/14da8cb7a7e684055055c2e5e20980e70e18caa7

**Comment by ritvikjain99** [comment]
@willemarcel I have pulled develop but this issue persists !

**Comment by willemarcel** [comment]
probably you didn't update the iD version
