### ISSUE TITLE
Start editor JOSM doesn't work with Safari

### ISSUE THREAD

**Issue by akimmig** [hotosm/tasking-manager#927]
I get the message:
"Dismiss, JOSM remote control did not respond. Do you have JOSM running and configured to be controlled remotely?"
It works with Chrome.

Safari Version 11.0.1 (12604.3.5.1.1)

**Comment by leonmvd** [comment]
I have the same issue, works in firefox and chrome but not with safari.

**Comment by verdy-p** [comment]
This is apparently a problem of security/authorization settings in Safari which blocks the query (probably against possible cross-site scripting attacks) from a javascript loaded from an external website in its own security domain (even if it's from a secured web site with HTTPS) to reach a port on the local host.

Safari is most probably "sandboxing" by default the web session and may require specific authorizations or configuration in the browser to not block this trafic (even if it comes from a javascript running in the local host used by the current host user, it remains in the remote domain from where the javascript originates, as if this was still coming from an external site which does not belong to the local host domain). If Safari is configurable, there may be some "whitelist" of remote domain names authorized to send trafic to the local host with websockets created in the javascript engine.

But may be Safari displays an alert icon in the top bar showing that some trafic was blocked (just like there are now blocks by default for privacy reasons against Flash, or against javascripts that want to open popups, or against autoplayed sounds/videos. This will probably affect other browsers (including Chrome, Firefox, or Edge) which may take similar restrictions to protect users, by better sandboxing the javascript engine or other browser plugins.

**Comment by gorn** [comment]
I have the same issue with forefox. I have manually added security exception so both http://localhost:8111 and https://lcoalhost:8112 show josm text, but the "Start editor" button stil does not work. I use Firefox 60 on latest Linux Mint

**Comment by ethan-nelson** [comment]
We've pushed an update to the staging server that may fix this--could you try it out at https://tasks-stage.hotosm.org and let me know if that is the case?

**Comment by akimmig** [comment]
Unfortunately I still get the message

"JOSM remote control did not respond. Do you have JOSM running and configured to be controlled remotely?"

when starting josm in Safari from  https://tasks-stage.hotosm.org <https://tasks-stage.hotosm.org/>

It works with Chrome.

Safari-Version: Version 11.1.2 (12605.3.8.1)
Josm version: 14066


Thanks for your efforts

Best
Arne

**Comment by twpol** [comment]
@akimmig Does the "Edit with Remote Control (JOSM or Merkaartor)" option on https://www.openstreetmap.org/ work in Safari?

The fix (which resolves the same problem in Edge, at least) attempts to implement the exact same mechanism as the main OSM website, although it ends up more complex due to needing to send multiple remote commands instead of just one.

**Comment by akimmig** [comment]
Hi James,

Sorry to tell you that it doesn’t´t work with Safari from openstreetmap neither. Josm is configured for remote control as you can see in the attached screenshot.

Thanks for trying to fix this issue.


Best,
Arne

**Comment by harry-wood** [comment]
hmm so there was an iframe fix for this bug https://github.com/hotosm/tasking-manager/issues/1000  which fixed it for firefox but not for safari.

For safari, my suggestion here: https://github.com/hotosm/tasking-manager/issues/1000#issuecomment-388635545  ...will work I think.

**Comment by pyrog** [comment]
Got this error message in the console (from OSM website):

> [blocked] The page at about:blank was not allowed to display insecure content from http://127.0.0.1:8111/load_and_zoom?left=-70.6644307209015&top=41.95700512499653&right=-70.65615190734864&bottom=41.95621870428267.

Safari Version 13.0.2 (14608.2.40.1.2)

**Comment by tomhughes** [comment]
That's a bug in safari, namely https://bugs.webkit.org/show_bug.cgi?id=171934.

**Comment by xamanu** [comment]
This came up again here: https://github.com/hotosm/tasking-manager/issues/2347

> Safari browser is blocking JOSM from loading due to CORS.

**Comment by willemarcel** [comment]
Old and solved issue
